accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('delete/',views.delete, name='delete'),
    path('password/', views.password, name='password'),
    path('profile/update/', views.profile_update, name='profile_update'),
    path('<int:user_id>/follow/', views.follow, name='follow'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_id>/',views.detail_movie, name='detail'),
    path('boxoffice/', views.boxoffice, name='boxoffice'),
    path('newmovie/',views.newmovie, name='newmovie'),
    path('recommend/<int:movie_id>', views.recommend),
    path('similar/<int:movie_id>', views.similar),
    path('createmovie', views.createmovie, name='createmovie'),
    path('createscore', views.createscore, name='createscore'),
    path('get_movie/',views.get_movie),
    path('get_genre/',views.get_genre),
    path('get_boxoffice/',views.get_boxoffice),
    path('get_recommend/<int:movie_id>', views.get_recommend),
    path('get_similar/<int:movie_id>', views.get_similar),
    path('get_comments/<int:movie_id>',views.get_comments),
    path('delete/comment/<int:comment_id>',views.delete_comment),
    # path('<int:movie_id>/score/new',views.new_score, name='new_score'),
    # path('<int:movie_id>/score/<int:score_id>/delete/',views.delete_score, name='delete_score'),
    # path('<int:movie_id>/like/', views.like, name='like'),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from accounts import views as accounts_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/',include('movies.urls')),
    path('accounts/',include('accounts.urls')),
    path('<str:username>/', accounts_views.people, name='people'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pjt/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"-->
    <!--    crossorigin="anonymous">-->
    <!--<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/"-->
    <!--    crossorigin="anonymous">-->
    <!--<link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.0/css/mdb.min.css" rel="stylesheet">-->
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.0/css/mdb.min.css" rel="stylesheet">
    {% if not people %}
    <link rel="stylesheet" href="{% static 'movie.css'%}">
    {% else %}
    <link rel="stylesheet" href="{% static 'people.css'%}">
    {% endif %}
    <link href="https://fonts.googleapis.com/css?family=Do+Hyeon|Nanum+Pen+Script" rel="stylesheet">
    <!--<link rel="icon" type="image/png" sizes="96x96" href="assets/favicon96x96.png">-->
    <script src="https://unpkg.com/axios/dist/axios.min.js">
        axios.defaults.xsrfCookieName = 'csrftoken'
        axios.defaults.xsrfHeaderName = "X-CSRFTOKEN"
    </script>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <link rel="shortcut icon" type="image⁄x-icon" href="https://st2.depositphotos.com/2068621/6008/v/950/depositphotos_60082317-stock-illustration-video-icon-on-white-background.jpg">
    <title>MRI</title>

</head>

<body class='bg-dark' id="body">
    <!-- navbar -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
        <a class="navbar-brand" href="{% url 'movies:index' %}">MRI|Movie-Recommandation-Information</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse " id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto ">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'movies:index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'movies:newmovie' %}" >New Movie</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'movies:boxoffice' %}" >Today Boxoffice</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown-555" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                          {{ user.username }}
                        </a>
                        <!--<a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink-555" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown-->
                        <!--</a>-->
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown-555">
                            <a href="{% url 'people' user.username %}">
                                {% if user.profile.image %}
                                <img src="{{ user.profile.image.url }}" class="rounded-circle col align-self-center" width="50" alt="{{ user.profile.image }}">
                                {% else %}
                                <img src="{% static 'basic1.jpg' %}" class="rounded-circle col align-self-center" width="50" alt="...">
                                {% endif %}
                            </a>
                            <a class="dropdown-item" href="{% url 'people' user.username %}">내정보</a>
                            <!--<a class="dropdown-item" href="{% url 'accounts:profile_update' %}">프로필 설정</a>-->
                            <a class="dropdown-item" href="{% url 'accounts:update' %}">계정 설정</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'accounts:logout' %}">로그아웃</a>
                        </div>
                      </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:signup' %}">SignUp</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">LogIn</a>
                        <form class="dropdown-menu dropdown-menu-xl-right p-3 bg-dark" aria-labelledby="navbarDropdown" action = "{% url 'accounts:login' %}" method ='post' >
                            {% csrf_token %}
                            <p class = "text-light">{{form.username.label}}</p>
                            <div class="form-group bg-light text-dark">
                                <!--<label for="exampleDropdownFormEmail2">ID</label>-->
        
                                <input type="text" class="form-control" id="exampleDropdownFormEmail2" placeholder="ID" name='username'>
                            </div>
                            <p class = "text-light">{{form.password.label}}</p>
                            <div class="form-group bg-light text-dark">
                                <!--<label for="exampleDropdownFormPassword2">Password</label>-->
                                <input type="password" class="form-control" id="exampleDropdownFormPassword2" placeholder="Password" name='password'>
                   
                            </div>
                          <button type="submit" class="btn btn-light">Sign in</button>
                        </form>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
 
    <!-- navbar -->
    <!-- layout -->
    <!-- header -->
    {% if not people %}
    <header id="header" class='row align-items-center justify-content-center' style='color:white;'>
        <h2 class='header-text text-center'>당신에게 어울리는 영화를 <br>추천해드립니다. </h2>
    </header>
    {% endif %}
    <!-- header -->
    {% block content %}
    {% endblock %}
    <p class='m-2'>-</p>
    <div class='m-5'>
        
    </div>
    <footer class='px-3 d-flex justify-content-between align-items-center fixed-bottom'>
        <span class="font-size : 30px; ">miz</span>
        <a href="#body" class='top'>
            <span style="font-size : 30px; color :white;">
                <i class="fas fa-caret-up"></i>
            </span>
        </a>
    </footer>
   
    <!--<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"-->
    <!--    crossorigin="anonymous"></script>-->
    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"-->
    <!--    crossorigin="anonymous"></script>-->
    <!--<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"-->
    <!--    crossorigin="anonymous"></script>-->
<!-- JQuery -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.8.0/js/mdb.min.js"></script>
</body>

</html>