accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('update/', views.update, name='update'),
    path('delete/',views.delete, name='delete'),
    path('password/', views.password, name='password'),
    path('profile/update/', views.profile_update, name='profile_update'),
    path('<int:user_id>/follow/', views.follow, name='follow'),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from accounts import views as accounts_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/',include('movies.urls')),
    path('accounts/',include('accounts.urls')),
    path('<str:username>/', accounts_views.people, name='people'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.conf import settings
from django.contrib.auth.models import AbstractUser

# Create your models here.
# 프로필
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=40, blank=True)
    introduction = models.TextField(blank=True)
    image = ProcessedImageField(
                    blank=True,
                    upload_to='profile/images',   # 저장위치
                    processors=[ResizeToFill(300,300)], # 처리할 작업 목록
                    format='JPEG',  # 저장 포맷
                    options={'quality':90}, # 옵션
                )

# 팔로우
class User(AbstractUser):
    followers = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followings')

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from .models import Profile

# 회원가입
class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ['username', 'email']
        

# 회원 정보 변경
class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'first_name', 'last_name',]
        
# 프로필 폼        
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['nickname', 'introduction', 'image',]

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import get_user_model,update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from .forms import CustomUserChangeForm, ProfileForm, CustomUserCreationForm
from .models import Profile
from django.contrib import messages
from django.contrib.auth.tokens import default_token_generator
from pjt import settings
# 회원가입
def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:index')
            
    if request.method == 'POST':
        signup_form = CustomUserCreationForm(request.POST)
        if signup_form.is_valid():
            user = signup_form.save()
            Profile.objects.create(user=user) # User의 Profile 생성
            auth_login(request, user)
            return redirect('movies:index')
    else:
        signup_form = CustomUserCreationForm()
    return render(request, 'accounts/signup.html', {'signup_form':signup_form})

# 로그인
def login(request):
    if request.user.is_authenticated:
        return redirect('movies:index')
    if request.method =='POST':
        login_form = AuthenticationForm(request, request.POST)
        if login_form.is_valid():
            auth_login(request, login_form.get_user())
            return redirect(request.GET.get('next') or 'movies:index')
    else:
        login_form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'login_form':login_form})

# 로그아웃
def logout(request):
    auth_logout(request)
    return redirect('movies:index')
    
# 내 정보
@login_required
def people(request, username):
    # get_user_model #=> User
    people = get_object_or_404(get_user_model(), username=username)
    profile = people.profile
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, request.FILES, instance=profile)
        if profile_form.is_valid():
            profile_form.save()
            return redirect('people', request.user.username)
    else:
        profile_form = ProfileForm(instance=profile)

    return render(request, 'accounts/people.html', {'people':people, 'profile_form': profile_form})
    
# 회원정보 업데이트
@login_required
def update(request):
    if request.method == 'POST':
        user_change_form= CustomUserChangeForm(request.POST, instance=request.user)
        if user_change_form.is_valid():
            user_change_form.save()
            return redirect('people', request.user.username)
    else:
        user_change_form = CustomUserChangeForm(instance=request.user)
    return render(request, 'accounts/update.html', {'user_change_form':user_change_form})
    
#회원 탈퇴   
@login_required
def delete(request):
    if request.method == 'POST':
        request.user.delete()
        return redirect('movies:index')
    return render(request, 'accounts/delete.html')
    
# 비밀번호 변경
@login_required
def password(request):
    if request.method == 'POST':
        password_change_form = PasswordChangeForm(request.user, request.POST)
        if password_change_form.is_valid():
            user = password_change_form.save()
            update_session_auth_hash(request, user)
            return redirect('people', request.user.username)
    else:
        password_change_form = PasswordChangeForm(request.user)
    return render(request, 'accounts/password.html', {'password_change_form':password_change_form})

# 프로필 업데이트
@login_required
def profile_update(request):
    profile = request.user.profile
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, request.FILES, instance=profile)
        if profile_form.is_valid():
            profile_form.save()
            return redirect('people', request.user.username)
    else:
        profile_form = ProfileForm(instance=profile)
    return render(request, 'accounts/profile_update.html', {
                                        'profile_form': profile_form,
                                    })
    
# 팔로우
def follow(request, user_id):
    people = get_object_or_404(get_user_model(), id=user_id)
    
    if request.user in people.followers.all():
        # unfollow
        people.followers.remove(request.user)
    else:
        # follow
        people.followers.add(request.user)
    
    return redirect('people', people.username)

accounts/templates/accounts/_people.html
{% load bootstrap4 %}

<div class="container ">
  <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="v-pills-like-tab" data-toggle="pill" href="#v-pills-like" role="tab" aria-controls="v-pills-like" aria-selected="false" style="color:white;">관심 영화</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="v-pills-friends-review-tab" data-toggle="pill" href="#v-pills-friends-review" role="tab" aria-controls="v-pills-friends-review" aria-selected="false" style="color:white;">친구 리뷰</a>
    </li>
    {% if user == people %}
      <li class="nav-item">
        <a class="nav-link" id="v-pills-profile-update-tab" data-toggle="pill" href="#v-pills-profile-update" role="tab" aria-controls="v-pills-profile-update" aria-selected="false" style="color:white;">프로필 수정</a>
      </li>
    {% endif %}
  </ul>
  <hr>
  <div class="tab-content" id="pills-tabContent">
    <div class="tab-pane fade show active" id="v-pills-like" role="tabpanel" aria-labelledby="v-pills-like-tab">{% include 'accounts/people/like.html' %}</div>
    <div class="tab-pane fade" id="v-pills-friends-review" role="tabpanel" aria-labelledby="v-pills-friends-review-tab">{% include 'accounts/people/friend_review.html' %}</div>
    {% if people == user %}
    <div class="tab-pane fade" id="v-pills-profile-update" role="tabpanel" aria-labelledby="v-pills-profile-update-tab">{% include 'accounts/profile_update.html' %}</div>
    <div class="tab-pane fade" id="v-pills-update" role="tabpanel" aria-labelledby="v-pills-update-tab">계정 설정</div>
    {% endif %}
  </div>
</div>

accounts/templates/accounts/delete.html
{% extends 'base.html' %}

{% block content %}

<h1>정말 삭제하시겠습니까?</h1>


<form method="POST">
    {% csrf_token %}
    <p>정말로 탈퇴하시겠습니까?</p>
    <input type="submit" value="탈퇴"/>
</form>

{% endblock%}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}

<h1>로그인</h1>

<form method="POST">
    {% csrf_token %}
    {{ login_form }}
    <input type="submit" value="Submit"/>
</form>

{% endblock %}

accounts/templates/accounts/password.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}

<div class="container">
    <h1>Password Change</h1>
    
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form password_change_form %}
        <input type="submit" value="Submit"/>
    </form>
</div>


{% endblock %}

accounts/templates/accounts/people.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block content %}



<header class='row align-items-center justify-content-center'>
    <h2 class='header-text text-center'>
        <div class="row text-light">
            <div class="col-3">
                <h1>
                    {% if people.profile.image %}
                    <img src="{{ people.profile.image.url }}" class="rounded-circle" width="150" alt="{{ people.profile.image }}">
                    {% else %}
                    <img src="{% static 'basic1.jpg' %}" class="rounded-circle" width="150" alt="...">
                    {% endif %}
                    <hr>
                </h1>
            </div>
            <!--팔로우-->
            <div class="col-4">
                <strong>{{ people.username }}</strong>
                {% if user != people %}
                    {% if user in people.followers.all %}
                    <a href="{% url 'accounts:follow' people.id %}"><i class="fas fa-user-check" style="color:white" ></i></a>
                    {% else %}
                    <a href="{% url 'accounts:follow' people.id %}"><i class="far fa-user" style="color:white" ></i></a>
                    {% endif %}
                {% endif %}
            </div>
            <div class="col-8" style="" >
                <i>Followers: </i> <i>{{ people.followers.count }}</i>
                <!--{% for follower in people.followers.all %}-->
                <!--    {{ follower }}-->
                <!--{% endfor %}-->
                <br>
                <i>Followings: </i> <i>{{ people.followings.count }}</i>
                <!--{% for following in people.followings.all %}-->
                <!--    {{ following }}-->
                <!--{% endfor %}-->
            </div>
        </div>
    </h2>
</header>
<hr>
<div class="container">
    {% if user == people %}
        <div>
            <a href="{% url 'accounts:update' %}" style="color :white;">계정 정보 수정</a>
        </div>
    {% endif %}
</div>

{% include 'accounts/_people.html' %}


{% endblock %}

accounts/templates/accounts/profile_update.html
{% load static %}
{% load bootstrap4 %}

<div class="container">
    <h1>Profile Edit</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form profile_form %}
        <input type="submit" value="Submit"/>
    </form>
</div>

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block content %}


<div class='m-3'></div>
<div class='m-5'> </div>
<div class="col-md-6 offset-md-3">
    <div class="card col bg-dark border-light" style="width: 50rem;">
        <img src="{% static 'signup.jpg' %}" class="card-img-top mt-2" alt="...">
        <div class="card-body text-light">
            <h5 class="card-title text-light">회원가입</h5>
            <form method="POST">
                {% csrf_token %}
                {% bootstrap_form signup_form %}
                <input type="submit" value="Submit"/>
            </form>
        </div>
    </div>
</div>
<!--<p>-</p> -->
<!--<div class='m-5'> <p></p> </div>-->
<!--<div class='m-5'> </div>-->


{% endblock %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}

<div class="container">
    <h1>User Edit</h1>
    
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form user_change_form %}
        <input type="submit" value="Submit"/>
    </form>
    
    
    <h3>User Delete</h3>
    
    <a href="{% url 'accounts:delete' %}" class="btn btn-danger">회원 탈퇴</a>
</div>


{% endblock %}